spring.application.name=spring-ai-basic
spring.ai.openai.chat.options.model=gpt-4o-mini-2024-07-18
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.embedding.enabled=true
spring.ai.openai.embedding.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.vectorstore.pinecone.apiKey=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=bbc-news
spring.ai.vectorstore.pinecone.host-url=https://bbc-news-xxxxxxx.svc.xxxx-xxxx-xxxx.pinecone.io
